spring:
  #配置thymeleaf模版
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    encoding: utf-8

  mvc:
    # 配置静态资源文件路径
    static-path-pattern: /static/**
  datasource:
    url: jdbc:mysql://192.168.3.53:3306/sbsm?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    #配置文件上传
    multipart:
      enabled: true
      location:
      max-file-size: 50MB
      max-request-size: 50MB

  # 配置redis集群
  redis:
    host: 192.168.3.53
    password: foo
    port: 6379
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-idle: 8 # 最大空闲
        min-idle: 0
        max-wait: 6000ms


  #Spring session配置session存储方式
  session:
    store-type: redis

  rabbitmq:
    host: 192.168.3.53
    port: 5672
    username: root
    password: root
    virtual-host: /



#配置项目启动端口
server:
  port: 8070
  servlet:
    context-path: /

#配置mybatis
mybatis:
#  type-aliases-package: com.snsprj.sbsm.model
  mapper-locations: classpath:mybatis/mapper/*.xml


#FTP服务器配置
ftp:
  host: 192.168.0.175
  port: 21
  username: ftpuser
  password: foo
  nginx:
    port: 8080 # nginx 开放的端口，访问ftp文件


#log
logging:
  config: classpath:logback.xml


